feat: add retag existing images (#88528)

diff --git a/ci-job-template.yml b/ci-job-template.yml
--- a/ci-job-template.yml
+++ b/ci-job-template.yml
@@ -155,6 +155,11 @@ parameters:
   type: string
   default: '4.7.0'
 
+  # Enable this to retag builded Docker images for tags instead of rebuilding them.
+- name: retagExistingImages
+  type: boolean
+  default: false
+
 jobs:
 - job: CI${{ parameters.id }}
   pool: '${{ parameters.agentPool }}'
@@ -168,10 +173,6 @@ jobs:
     # See: https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#gradle
     - name: GRADLE_USER_HOME
       value: ${{ parameters.gradleUserHome }}
-    - name: YQ_VERSION
-      value: v4.33.3
-    - name: YQ_BINARY
-      value: yq_linux_amd64
 
   steps:
     # Checkout all repositories
@@ -193,7 +194,9 @@ jobs:
       inputs:
         targetType: 'inline'
         script: |
+
           #!/bin/bash
+
           set -e
       
           if [ -z "${{ parameters.acrServiceConnection }}" ]; then
@@ -276,6 +279,7 @@ jobs:
               lockImages:                     ${{ parameters.lockImages }}
               preHookTemplate:                ${{ parameters.preHookTemplate }}
               postHookTemplate:               ${{ parameters.postHookTemplate }}
+              retagExistingImages:            ${{ parameters.retagExistingImages }}
 
               # Code Analysis
               sonarQubeRunAnalysis:           ${{ parameters.sonarQubeEnabled }}
@@ -336,9 +340,149 @@ jobs:
         jdkArchitectureOption: 'x64'
         jdkSourceOption: 'PreInstalled'
 
+    - task: AzureCLI@2
+      timeoutInMinutes: 5
+      condition: and(succeeded(), eq('${{ parameters.retagExistingImages }}', true), eq(variables.isVersion, true), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
+      displayName: "Retag existing Images"
+      env:
+        IMAGE_ARTIFACT_FILE_PATH: $(Agent.TempDirectory)/image/imageProperties.yaml
+        REGISTRY: ${{ parameters.acr }}
+      inputs:
+        azureSubscription: '$(REPO_SERVICE_CONNECTION_ARM)'
+        scriptType: bash
+        scriptLocation: inlineScript
+        inlineScript: |
+
+          #!/bin/bash
+
+          # This script pulls a Docker image from a registry, renames/retags it with a target version obtained from Gradle, and pushes it back to the same registry.
+
+          # Log in to Azure DevOps
+          echo "$(System.AccessToken)" | az devops login --organization "$(System.CollectionUri)"
+
+          # Get the last successful build ID for this commit
+          LAST_SUCCESS_BUILD_ID=$(az pipelines runs list \
+            --org $(System.CollectionUri) \
+            --project $(System.TeamProjectId) \
+            --pipeline-ids $(System.DefinitionId) \
+            --query-order FinishTimeDesc \
+            --result succeeded \
+            --status completed \
+            --query "[?sourceVersion=='$(Build.SourceVersion)'].id | [0]" -o tsv
+          )
+
+          echo "LAST_SUCCESS_BUILD_ID: ${LAST_SUCCESS_BUILD_ID}"
+
+          # Check if the variable is empty
+          if [[ -z "${LAST_SUCCESS_BUILD_ID}" ]]; then
+            echo "The variable LAST_SUCCESS_BUILD_ID is empty."
+            exit 0
+          fi
+
+          # Find the download URL of the artifact
+          ARTIFACT_DOWNLOAD_URL=$(az pipelines runs artifact list \
+            --run-id "${LAST_SUCCESS_BUILD_ID}" \
+            --org "$(System.CollectionUri)" \
+            --project "$(System.TeamProjectId)" \
+            --query "[?name=='image_artifacts'].resource.downloadUrl" -o tsv)
+
+          echo "ARTIFACT_DOWNLOAD_URL: ${ARTIFACT_DOWNLOAD_URL}"
+
+          # Check if the variable is empty
+          if [[ -z "${ARTIFACT_DOWNLOAD_URL}" ]]; then
+            echo "The variable ARTIFACT_DOWNLOAD_URL is empty."
+            exit 0
+          fi
+
+          curl \
+            -o $(Agent.TempDirectory)/artifact.zip \
+            -L "${ARTIFACT_DOWNLOAD_URL}" \
+            -H "Authorization: Bearer $(System.AccessToken)"
+          
+          unzip -q $(Agent.TempDirectory)/artifact.zip -d $(Agent.TempDirectory)
+
+          # Check if the image artifact file exists
+          if [[ ! -f "${IMAGE_ARTIFACT_FILE_PATH}" ]]; then
+            echo "File: ${IMAGE_ARTIFACT_FILE_PATH} not exists."
+            exit 0
+          fi
+
+          IMAGE_TAG=$(yq '.images[0].tag // ""' ${IMAGE_ARTIFACT_FILE_PATH})
+          IMAGE_DIGEST=$(yq '.images[0].digest // ""' ${IMAGE_ARTIFACT_FILE_PATH})
+          IMAGE_NAME=$(yq '.images[0].name // ""' ${IMAGE_ARTIFACT_FILE_PATH})
+          IMAGE_REGISTRY=$(yq '.images[0].registry // ""' ${IMAGE_ARTIFACT_FILE_PATH})
+
+          # Check if IMAGE_TAG, IMAGE_DIGEST, IMAGE_NAME or IMAGE_REGISTRY are empty or null
+          if [[ -z "${IMAGE_TAG}" || -z "${IMAGE_DIGEST}" || -z "${IMAGE_NAME}" || -z "${IMAGE_REGISTRY}" ]]; then
+            echo "##[error] Invalid image mapping. IMAGE_TAG, IMAGE_DIGEST, IMAGE_NAME or IMAGE_REGISTRY is empty or null."
+            exit 0
+          fi
+
+          # Check if the image registry matches the expected registry
+          if [[ "${IMAGE_REGISTRY}" != "${REGISTRY}" ]]; then
+            echo "The strings REGISTRY and IMAGE_REGISTRY are not equal."
+            exit 0
+          fi
+
+          # Get the image digest from the Azure Container Registry
+          ACR_IMAGE_DIGEST=$(az acr repository show \
+            -n "${IMAGE_REGISTRY}" \
+            --image "${IMAGE_NAME}@${IMAGE_DIGEST}" \
+            --query "digest" \
+            -o tsv)
+
+          echo "ACR_IMAGE_DIGEST: ${ACR_IMAGE_DIGEST}"
+
+          # Check if the variable is empty
+          if [[ -z "${ACR_IMAGE_DIGEST}" ]]; then
+            echo "The variable ACR_IMAGE_DIGEST is empty."
+            exit 0
+          fi
+
+          # Check if the image digest matches the expected digest
+          if [[ "${ACR_IMAGE_DIGEST}" != "${IMAGE_DIGEST}" ]]; then
+            echo "The strings ACR_IMAGE_DIGEST and IMAGE_DIGEST are not equal."
+            exit 0
+          fi
+
+          # Change to the project directory
+          cd "${{ parameters.projectPath }}"
+
+          # Get the target image version info from Gradle
+          TARGET_IMAGE_VERSION_INFO=$(./gradlew showVersion ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID="$(Build.BuildId)")
+          echo "TARGET_IMAGE_VERSION_INFO: ${TARGET_IMAGE_VERSION_INFO}"
+
+          # Extract the target version from the output
+          TARGET_VERSION=$(echo "$TARGET_IMAGE_VERSION_INFO" | grep -A 1 "GitFlow version is" | tail -n 1 | cut -d' ' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+          
+          echo "TARGET_VERSION: ${TARGET_VERSION}"
+
+          # Check if the variable is empty
+          if [[ -z "${TARGET_VERSION}" ]]; then
+            echo "The variable TARGET_VERSION is empty."
+            exit 0
+          fi
+
+          # Pull the Docker image
+          docker pull "${IMAGE_REGISTRY}/${IMAGE_NAME}@${IMAGE_DIGEST}" || exit 0
+
+          # Echo the pull success message
+          echo "Docker image '${IMAGE_REGISTRY}/${IMAGE_NAME}@${IMAGE_DIGEST}' was successfully pulled."
+
+          # Rename and push the Docker image
+          docker tag "${IMAGE_REGISTRY}/${IMAGE_NAME}@${IMAGE_DIGEST}" "${IMAGE_REGISTRY}/${IMAGE_NAME}:${TARGET_VERSION}" || exit 0
+          docker push "${IMAGE_REGISTRY}/${IMAGE_NAME}:${TARGET_VERSION}" || exit 0
+
+          # Echo the push success message
+          echo "Docker image was successfully pushed to the repository '${IMAGE_REGISTRY}/${IMAGE_NAME}:${TARGET_VERSION}'."
+
+          echo "##vso[task.setvariable variable=imageRetagged;]true"
+          echo "##vso[task.setvariable variable=imageRetaggedName;]${IMAGE_REGISTRY}/${IMAGE_NAME}:${TARGET_VERSION}"
+
     - task: Gradle@3
       timeoutInMinutes: 10
       displayName: Check version
+      condition: and(succeeded(), ne(variables.imageRetagged, true))
       continueOnError: true
       inputs:
         cwd: ${{ parameters.projectPath }}
@@ -352,6 +496,7 @@ jobs:
 
     - task: Gradle@3
       displayName: Clean up container (start)
+      condition: and(succeeded(), ne(variables.imageRetagged, true))
       continueOnError: true
       inputs:
         cwd: ${{ parameters.projectPath }}
@@ -367,6 +512,7 @@ jobs:
     # the task contains the publishing of test results
     - task: Gradle@3
       displayName: Gradle build
+      condition: and(succeeded(), ne(variables.imageRetagged, true))
       continueOnError: false
       inputs:
         cwd: ${{ parameters.projectPath }}
@@ -388,7 +534,7 @@ jobs:
 
     - task: Gradle@3
       displayName: Gradle geb tests
-      condition: and(succeeded(), eq('${{ parameters.runGebTest }}', 'true'))
+      condition: and(succeeded(), eq('${{ parameters.runGebTest }}', 'true'), ne(variables.imageRetagged, true))
       continueOnError: false
       inputs:
         cwd: ${{ parameters.projectPath }}
@@ -403,7 +549,7 @@ jobs:
 
     - task: CmdLine@2
       displayName: docker write logs geb tests
-      condition: and(succeededOrFailed(), eq('${{ parameters.runGebTest }}', 'true'))
+      condition: and(succeededOrFailed(), eq('${{ parameters.runGebTest }}', 'true'), ne(variables.imageRetagged, true))
       timeoutInMinutes: 5
       inputs:
         workingDirectory: ${{ parameters.projectPath }}
@@ -421,6 +567,7 @@ jobs:
     # the task contains the publishing of test results
     - task: Gradle@3
       displayName: Gradle publish artifacts
+      condition: and(succeeded(), ne(variables.imageRetagged, true))
       continueOnError: false
       inputs:
         cwd: ${{ parameters.projectPath }}
@@ -435,32 +582,16 @@ jobs:
 
     - task: PublishPipelineArtifact@1
       timeoutInMinutes: 5
+      condition: and(succeededOrFailed(), ne(variables.imageRetagged, true))
       displayName: Provide developer files logs for tests
       inputs:
         targetPath: '${{ parameters.projectPath }}/build/ishunitrunner'
         artifactType: 'pipeline'
         artifactName: ishUnitTest_artifacts
-      condition: succeededOrFailed()
 
     #
     # Post steps
     #
-
-    # Install YQ
-    - task: Bash@3
-      displayName: 'Install yq'
-      env:
-        VERSION: $(YQ_VERSION)
-        BINARY: $(YQ_BINARY)
-      timeoutInMinutes: 2
-      inputs:
-        targetType: 'inline'
-        script: |
-          #!/bin/bash
-          set -e
-  
-          sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
-          sudo chmod +x /usr/bin/yq
     
     # Generate a build information file and push it as a pipeline artifact.
     - task: Bash@3
@@ -471,58 +602,50 @@ jobs:
       inputs:
         targetType: 'inline'
         script: |
+
           #!/bin/bash
+
           set -e
 
-          #######################################
           # This script reads the labels of a Docker image and creates an imageProperty file.
-          # Globals:
-          #   DOCKER_IMAGE_DIRECTORY: Path to the directory where the 'imageId' file can be found.
-          # Arguments:
-          #   None
-          #######################################
-
-          ###############################################################
-          # Script Parameters                                           #
-          ###############################################################
 
           # Create a temporary folder for storing intermediate files
-          TMP_CUSTOM_DIR="$(mktemp -d -t ci-icm-XXXXXXXXXX)"
+          TMP_CUSTOM_DIR="$(mktemp -d -p $(Agent.TempDirectory) -t ci-icm-XXXXXXXXXX)"
           IMAGE_PROPERTIES_FILE="${TMP_CUSTOM_DIR}/imageProperties.yaml"
 
-          ###############################################################
-          # Script                                                      #
-          ###############################################################
+          # Sets IMAGE_NAME based on image tagging conditions or file search in DOCKER_IMAGE_DIRECTORY
+          if [[ "$(imageRetagged)" == "true" ]] && [[ -n "$(imageRetaggedName)" ]]; then
+            IMAGE_NAME="$(imageRetaggedName)"
+          elif [ -n "${DOCKER_IMAGE_DIRECTORY}" ]; then
+            # Use 'find' to locate files ending in "-imageId.txt".
+            # Sort the list by modification time (newest first).
+            # Only return the first file in the list (the newest).
+            IMAGE_FILE=$(find "${DOCKER_IMAGE_DIRECTORY}" -name '*-imageId.txt' -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
 
-          # Check if the image directory variable is set
-          if [ -z "${DOCKER_IMAGE_DIRECTORY}" ]; then
-            echo "ERROR: DOCKER_IMAGE_DIRECTORY variable is not set"
+            # Check if an image file was found
+            if [[ -z "${IMAGE_FILE}" ]]; then
+              echo "ERROR: No image file found in ${DOCKER_IMAGE_DIRECTORY}"
+              exit 1
+            fi
+  
+            # Check if the image file exists
+            if [[ ! -f "${IMAGE_FILE}" ]]; then
+              echo "ERROR: ${IMAGE_FILE} does not exist"
+              exit 1
+            fi
+  
+            # Extract the image name from the file
+            IMAGE_NAME=$(cat "${IMAGE_FILE}" | tr -d '\n\r')
+          else
+            echo "ERROR: No valid method to obtain the ImageId."
             exit 1
           fi
 
-          # Use 'find' to locate files ending in "-imageId.txt".
-          # Sort the list by modification time (newest first).
-          # Only return the first file in the list (the newest).
-          IMAGE_FILE=$(find "${DOCKER_IMAGE_DIRECTORY}" -name '*-imageId.txt' -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
-
-          # Check if an image file was found
-          if [ -z "${IMAGE_FILE}" ]; then
-            echo "ERROR: No image file found in ${DOCKER_IMAGE_DIRECTORY}"
-            exit 1
-          fi
-
-          # Check if the image file exists
-          if [ ! -f "${IMAGE_FILE}" ]; then
-            echo "ERROR: ${IMAGE_FILE} does not exist"
-            exit 1
-          fi
-
-          # Extract the image name from the file
-          IMAGE_NAME=$(cat "${IMAGE_FILE}" | tr -d '\n\r')
+          echo "IMAGE_NAME: ${IMAGE_NAME}"
 
           # Check if the image name is valid
-          if [ -z "${IMAGE_NAME}" ]; then
-            echo "ERROR: Image name not found in ${IMAGE_FILE}"
+          if [[ -z "${IMAGE_NAME}" ]]; then
+            echo "ERROR: Image name is empty"
             exit 1
           fi
 
@@ -530,7 +653,7 @@ jobs:
           IFS=':' read -r REPOSITORY TAG <<< "${IMAGE_NAME}"
 
           # Check if the repository and tag are valid
-          if [ -z "${REPOSITORY}" ] || [ -z "${TAG}" ]; then
+          if [[ -z "${REPOSITORY}" ]] || [[ -z "${TAG}" ]]; then
             echo "ERROR: Invalid image name format in ${IMAGE_FILE}"
             exit 1
           fi
@@ -539,13 +662,17 @@ jobs:
           IMAGE_BASE_NAME="${REPOSITORY#*/}"
           REGISTRY="${REPOSITORY%%/*}"
 
+          # Get Image digest
+          IMAGE_DIGIST=$(docker image inspect --format='{{index .RepoDigests 0}}' "${IMAGE_NAME}" | cut -d'@' -f2)
+
           # Generate YAML file
-          cat <<EOF > ${IMAGE_PROPERTIES_FILE}
+          cat <<EOF > "${IMAGE_PROPERTIES_FILE}"
           images:
             - type: icm-customization
               tag: ${TAG}
               name: ${IMAGE_BASE_NAME}
               registry: ${REGISTRY}
+              digest: ${IMAGE_DIGIST}
               buildWith: []
           EOF
 
@@ -577,7 +704,7 @@ jobs:
             ELEMENT_VALUE=$(echo "${IMAGE_LABELS}" | jq --arg key "${ELEMENT_KEY}" -rc '.[$key]')
 
             # Check if the ELEMENT_VALUE is not empty
-            if [ -z "${ELEMENT_VALUE}" ]; then
+            if [[ -z "${ELEMENT_VALUE}" ]]; then
               echo "The 'ELEMENT_VALUE' variable is empty."
               exit 1
             fi
@@ -619,20 +746,20 @@ jobs:
     - task: PublishPipelineArtifact@1
       timeoutInMinutes: 5
       displayName: Provide geb test log files
+      condition: and(succeededOrFailed(), eq('${{ parameters.runGebTest }}', 'true'), ne(variables.imageRetagged, true))
       inputs:
         targetPath: '${{ parameters.projectPath }}/build/geb'
         artifactType: 'pipeline'
         artifactName: geb_test_log_files${{ parameters.id }}
-      condition: and(succeededOrFailed(), eq('${{ parameters.runGebTest }}', 'true'))
 
     - task: PublishPipelineArtifact@1
       timeoutInMinutes: 5
       displayName: Provide developer files logs
+      condition: and(succeededOrFailed(), ne(variables.imageRetagged, true))
       inputs:
         targetPath: '${{ parameters.projectPath }}/build/server/logs'
         artifactType: 'pipeline'
         artifactName: build_artifacts${{ parameters.id }}
-      condition: succeededOrFailed()
 
 #    - task: PublishPipelineArtifact@1
 #      displayName: Provide developer files Geb tests (sub project my_geb_test)
@@ -661,7 +788,7 @@ jobs:
     # then the generated Docker images in the ACR will be made non-overwritable and non-deletable.
     - task: AzureCLI@2
       timeoutInMinutes: 5
-      condition: and(succeeded(), eq('${{ parameters.lockImages }}', true), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
+      condition: and(succeeded(), eq('${{ parameters.lockImages }}', true), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables.isVersion, true))
       displayName: "Set image attributes"
       env:
         TAG: $(tag)
