PR: imageProperties as yaml  (#1)
* fix: make getbTest completely deactivatable

* feat: imageProperties as yaml

---------

Co-authored-by: Moritz Karsch <MKarsch@intershop.com>

diff --git a/ci-job-template.yml b/ci-job-template.yml
--- a/ci-job-template.yml
+++ b/ci-job-template.yml
@@ -4,39 +4,37 @@
 ################################################################################
 parameters:
 
-  # Has to be set, if ci-job-template.yml is used in a loop, for two reasons:
-  # - to make each job-name unique,
-  # - to extend names of files, which are published in extensions.
-  # For this reason id must consitst of characters, numbers and _ only.
+  # Identifies each job uniquely when ci-job-template.yml is used in a loop. 
+  # Can only contain characters, numbers, and underscores.
+  # Also used to extend names of files published in extensions.
 - name: id
   type: string
   default: ''
   
-  # Enables an easy integration with custom jobs. The parameter will be passed
-  # as is to the 'dependsOn' property of the job.
+  # Enables an easy integration with custom jobs. 
+  # The parameter will be passed as is to the 'dependsOn' property of the job.
 - name: dependsOn
   type: string
   default: ''
 
-  # Enables an easy integration with custom jobs. The parameter will be passed
-  # as is to the 'condition' property of the job.
+  # Enables an easy integration with custom jobs. 
+  # The parameter will be passed as is to the 'condition' property of the job.
 - name: condition
   type: string
   default: ''
 
-  # Every partner has it's own agent-pool, therefore the name of the pool cannot
-  # be hardcoded in the pipeline template.
+  # Specifies the name of the agent pool.
+  # The pool name can't be hardcoded in the pipeline template.
 - name: agentPool
   type: string
   default: ''
 
-  # Service connection to the Docker repository
+  # Name of the Service connection to the Docker repository
 - name: dockerRepoICMServiceConnection
   type: string
   default: ''
 
-  # Name of Docker repository, containing the IOM product images.
-  # Overwrites the property intershop.docker.repo of IOM project.
+  # Name of Docker repository, containing the ICM-customization product images.
 - name: dockerRepoICM
   type: string
   default: ''
@@ -46,7 +44,7 @@ parameters:
   type: string
   default: ''
 
-  # Service connection to the ACR of the project.
+  # Name of the service connection to the ACR of the project.
 - name: acrServiceConnection
   type: string
   default: ''
@@ -56,7 +54,7 @@ parameters:
   type: string
   default: ''
 
-  # Name of the repository 
+  # Specifies the name of the repository. 
 - name: projectPath
   type: string
   default: '$(Build.Repository.Name)'
@@ -78,12 +76,12 @@ parameters:
   type: string
   default: '-PrepoUser=PAT -PrepoPassword=$(System.AccessToken)'
 
-  #
+  # Value of the GRADLE_USER_HOME variable
 - name: gradleUserHome
   type: string
   default: '$(Pipeline.Workspace)/.gradle'
  
-  # 
+  # Prefix of the GebTest containers
 - name: containerPrefix
   type: string
   default: '$(Build.Repository.Name)'
@@ -93,12 +91,12 @@ parameters:
   type: number
   default: 300
 
-  # 'true' if future jobs should run even if this job fails; defaults to 'false'
+  # Specifies whether future jobs should run even if this job fails; defaults to 'false'.
 - name: jobContinueOnError
   type: boolean
   default: false
 
-  # 'false' if the gebTest task is not to be executed; defaults to 'true'
+  # Specifies whether all gebTest task should run; defaults to 'true'.
 - name: runGebTest
   type: boolean
   default: true
@@ -113,7 +111,6 @@ parameters:
   type: string
   default: 'startMSSQL dbPrepare test ishUnitTestReport -x=containerClean'
 
-
 jobs:
 - job: CI${{ parameters.id }}
   pool: '${{ parameters.agentPool }}'
@@ -127,6 +124,10 @@ jobs:
     # See: https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#gradle
     - name: GRADLE_USER_HOME
       value: ${{ parameters.gradleUserHome }}
+    - name: YQ_VERSION
+      value: v4.33.3
+    - name: YQ_BINARY
+      value: yq_linux_amd64
 
   steps:
     - checkout: self
@@ -160,10 +161,6 @@ jobs:
           fi
           if [ -z "${{ parameters.dockerRepoICM }}" ]; then
             echo "##[error] Parameter dockerRepoICM must not be empty!"
-            exit 1
-          fi
-          if [ -z "${{ parameters.acrServiceConnection }}" ]; then
-            echo "##[error] Parameter acrServiceConnection must not be empty!"
             exit 1
           fi
           if [ -z "${{ parameters.acr }}" ]; then
@@ -379,6 +376,20 @@ jobs:
       condition: succeededOrFailed()
 
     - task: Bash@3
+      displayName: 'Install yq'
+      env:
+        VERSION: $(YQ_VERSION)
+        BINARY: $(YQ_BINARY)
+      timeoutInMinutes: 2
+      inputs:
+        targetType: 'inline'
+        script: |
+          #!/bin/bash
+          set -e
+  
+          sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
+          sudo chmod +x /usr/bin/yq
+    - task: Bash@3
       displayName: Create Image Version Overview
       timeoutInMinutes: 5
       env:
@@ -390,7 +401,7 @@ jobs:
           set -e
 
           #######################################
-          # This script reads the labels of a Docker image and creates an imageProperties file.
+          # This script reads the labels of a Docker image and creates an imageProperty file.
           # Globals:
           #   DOCKER_IMAGE_DIRECTORY: Path to the directory where the 'imageId' file can be found.
           # Arguments:
@@ -401,124 +412,130 @@ jobs:
           # Script Parameters                                           #
           ###############################################################
 
-          # Path to the directory where the 'imageId' file can be found.
-          DOCKER_IMAGE_DIRECTORY=${DOCKER_IMAGE_DIRECTORY}
-
-          echo "DOCKER_IMAGE_DIRECTORY: $DOCKER_IMAGE_DIRECTORY"
-          # Check if the DOCKER_IMAGE_FILE variable is empty
-          if [ -z "${DOCKER_IMAGE_DIRECTORY}" ]; then
-              echo "The DOCKER_IMAGE_DIRECTORY variable is empty."
-              exit 1
-          fi
-
           # Create a temporary folder for storing intermediate files
-          TMP_CUSTOM_DIR=$(mktemp -d -t ci-icm-XXXXXXXXXX)
-          imagePropertiesFile="${TMP_CUSTOM_DIR}/imageProperties"
+          TMP_CUSTOM_DIR="$(mktemp -d -t ci-icm-XXXXXXXXXX)"
+          IMAGE_PROPERTIES_FILE="${TMP_CUSTOM_DIR}/imageProperties.yaml"
 
           ###############################################################
           # Script                                                      #
           ###############################################################
 
-          # Use find to locate files ending in "-imageId.txt"
-          # Sort the list by modification time (newest first)
-          # Only return the first file in the list (the newest)
-          DOCKER_IMAGE_FILE=$(find "${DOCKER_IMAGE_DIRECTORY}" -name '*-imageId.txt' -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
-
-          # Check if the DOCKER_IMAGE_FILE variable is empty
-          if [ -z "${DOCKER_IMAGE_FILE}" ]; then
-              echo "The DOCKER_IMAGE_FILE variable is empty."
-              exit 1
-          fi
-
-          # Check if the file containing the Docker image name is present
-          if [ ! -f "${DOCKER_IMAGE_FILE}" ]; then
-              echo "The file ${DOCKER_IMAGE_FILE} is not present."
-              exit 1
-          fi
-
-          # Read the content of the file, which contains the Docker image name
-          content=$(cat "${DOCKER_IMAGE_FILE}")
-          echo "Docker image name: ${content}"
-
-          # Check if the content variable is empty
-          if [ -z "${content}" ]; then
-              echo "The content variable is empty."
-              exit 1
-          fi
-
-          # Split the Docker image name into repository and image tag
-          IFS=':' read -r repository tag <<< "$content"
-
-          # Check if repository and tag are not empty
-          if [ -z "${repository}" ] || [ -z "${tag}" ]; then
-              echo "The repository and/or tag is empty."
-              exit 1
-          fi
-
-          # Remove the registry part from the repository name
-          repositoryWithOutRegistry="${repository#*/}"
-
-          # Write the repository name and tag to the imageProperties file
-          echo "build=${repositoryWithOutRegistry}" > ${imagePropertiesFile}
-          echo "${repositoryWithOutRegistry}.version=${tag}" >> ${imagePropertiesFile}
-
-          # Check if the Docker image is present on the local system
-          if docker image inspect ${repository}:${tag} >/dev/null 2>&1; then
-            echo "The Docker image ${repository}:${tag} is present on the local system."
-          else
-            echo "The Docker image ${repository}:${tag} is NOT present on the local system."
+          # Check if the image directory variable is set
+          if [ -z "${DOCKER_IMAGE_DIRECTORY}" ]; then
+            echo "ERROR: DOCKER_IMAGE_DIRECTORY variable is not set"
             exit 1
           fi
 
+          # Use 'find' to locate files ending in "-imageId.txt".
+          # Sort the list by modification time (newest first).
+          # Only return the first file in the list (the newest).
+          IMAGE_FILE=$(find "${DOCKER_IMAGE_DIRECTORY}" -name '*-imageId.txt' -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" ")
+
+          # Check if an image file was found
+          if [ -z "${IMAGE_FILE}" ]; then
+            echo "ERROR: No image file found in ${DOCKER_IMAGE_DIRECTORY}"
+            exit 1
+          fi
+
+          # Check if the image file exists
+          if [ ! -f "${IMAGE_FILE}" ]; then
+            echo "ERROR: ${IMAGE_FILE} does not exist"
+            exit 1
+          fi
+
+          # Extract the image name from the file
+          IMAGE_NAME=$(cat "${IMAGE_FILE}" | tr -d '\n\r')
+
+          # Check if the image name is valid
+          if [ -z "${IMAGE_NAME}" ]; then
+            echo "ERROR: Image name not found in ${IMAGE_FILE}"
+            exit 1
+          fi
+
+          # Extract the repository and tag from the image name
+          IFS=':' read -r REPOSITORY TAG <<< "${IMAGE_NAME}"
+
+          # Check if the repository and tag are valid
+          if [ -z "${REPOSITORY}" ] || [ -z "${TAG}" ]; then
+            echo "ERROR: Invalid image name format in ${IMAGE_FILE}"
+            exit 1
+          fi
+
+          # Split image name in registry and image base name
+          IMAGE_BASE_NAME="${REPOSITORY#*/}"
+          REGISTRY="${REPOSITORY%%/*}"
+
+          # Generate YAML file
+          cat <<EOF > ${IMAGE_PROPERTIES_FILE}
+          images:
+            - type: icm-customization
+              tag: ${TAG}
+              name: ${IMAGE_BASE_NAME}
+              registry: ${REGISTRY}
+              buildWith: []
+          EOF
+
           # Read all labels from the Docker image
-          labels="$(docker inspect -f '{{ json .Config.Labels}}' ${repository}:${tag})"
+          IMAGE_LABELS="$(docker inspect -f '{{ json .Config.Labels}}' ${IMAGE_NAME})"
 
           # Check if the label 'build.with' exists
-          if ! echo "${labels}" | jq 'has("build.with")' | grep -q true; then
-            echo "The 'build.with' label was not found in ${labels}."
+          if ! echo "${IMAGE_LABELS}" | jq 'has("build.with")' | grep -q true; then
+            echo "The 'build.with' label was not found in ${IMAGE_LABELS}."
             exit 1
           fi
 
           # Read the value of the 'build.with' label
-          build_with=$(echo "${labels}" | jq --arg key "build.with" -r '.[$key]')
-          # Write the 'build.with' propertie to to the imageProperties file
-          echo "build.with=${build_with}" >> ${imagePropertiesFile}
+          BUILD_WITH_VALUE=$(echo "${IMAGE_LABELS}" | jq --arg key "build.with" -r '.[$key]')
 
           # Iterate over the comma-separated list of elements in the 'build.with' label
-          IFS=',' read -ra elements <<< "$build_with"
-          for element in "${elements[@]}"; do
-            echo "## Element: ${element}"
+          IFS=',' read -ra ELEMENTS <<< "$BUILD_WITH_VALUE"
+          for ELEMENT in "${ELEMENTS[@]}"; do
+            echo "## Element: ${ELEMENT}"
 
-            # Check if the label '<element>.version' exists in the Docker image
-            elementKey="${element}.version"
-            if ! echo "${labels}" | jq --arg key "${elementKey}" 'has($key)' | grep -q true; then
-              echo "The '${elementKey}' label was not found in ${labels}."
+            # Check if the label '<ELEMENT>.version' exists in the Docker image
+            ELEMENT_KEY="${ELEMENT}.version"
+            if ! echo "${IMAGE_LABELS}" | jq --arg key "${ELEMENT_KEY}" 'has($key)' | grep -q true; then
+              echo "The '${ELEMENT_KEY}' label was not found in ${IMAGE_LABELS}."
               exit 1
             fi
             
-            # Read the value for the '<element>.version' label
-            elementValue=$(echo "${labels}" | jq --arg key "${elementKey}" -rc '.[$key]')
+            # Read the value for the '<ELEMENT>.version' label
+            ELEMENT_VALUE=$(echo "${IMAGE_LABELS}" | jq --arg key "${ELEMENT_KEY}" -rc '.[$key]')
 
-            # Check if the elementValue is not empty
-            [ -z "${elementValue}" ] && echo "The 'elementValue' variable is empty." && exit 1
+            # Check if the ELEMENT_VALUE is not empty
+            if [ -z "${ELEMENT_VALUE}" ]; then
+              echo "The 'ELEMENT_VALUE' variable is empty."
+              exit 1
+            fi
 
-            # Write the '<element>.version' label and value to the imageProperties file
-            echo "${elementKey}=${elementValue}" >> ${imagePropertiesFile}
+            # Write the buildWith image to the IMAGE_PROPERTIES_FILE
+            ELEMENT_IMAGE_STRING=$(cat <<EOF
+            {
+              "type": "buildWith",
+              "tag": "${ELEMENT_VALUE}",
+              "name": "${ELEMENT}",
+              "registry": "intershop"
+            }
+          EOF
+          )
+
+            echo "ELEMENT_IMAGE_STRING = $(echo "$ELEMENT_IMAGE_STRING" | jq -rc)"
+            ELEMENT_IMAGE_OBJECT="$ELEMENT_IMAGE_STRING" \
+            yq -i '.images[0].buildWith += eval(strenv(ELEMENT_IMAGE_OBJECT))' ${IMAGE_PROPERTIES_FILE}
           done
   
           # Print the contents of the imageProperties file
-          echo "###### File ${imagePropertiesFile} ######"
-          cat ${imagePropertiesFile}
+          echo "###### File ${IMAGE_PROPERTIES_FILE} ######"
+          cat ${IMAGE_PROPERTIES_FILE}
           echo "###### File end ######"
 
           # Upload the imageProperties file as an artifact
-          echo "##vso[artifact.upload containerfolder=image;artifactname=image_artifacts]${imagePropertiesFile}"
+          echo "##vso[artifact.upload containerfolder=image;artifactname=image_artifacts]${IMAGE_PROPERTIES_FILE}"
 
           cat >> "$(Pipeline.Workspace)/config${{ parameters.id }}.md" <<EOF
 
           # Created Docker image
-              id:                             ${repository}:${tag}
-              
+              id:                             ${REPOSITORY}:${TAG}
           EOF
 
     - task: PublishPipelineArtifact@1
@@ -528,7 +545,7 @@ jobs:
         targetPath: '${{ parameters.projectPath }}/build/geb'
         artifactType: 'pipeline'
         artifactName: geb_test_log_files${{ parameters.id }}
-      condition: succeededOrFailed()
+      condition: and(succeededOrFailed(), eq('${{ parameters.runGebTest }}', 'true'))
 
     - task: PublishPipelineArtifact@1
       timeoutInMinutes: 5
